name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

jobs:
  golangci:
    uses: turbot/steampipe-workflows/.github/workflows/golangci-lint.yml@main
    with:
      timeout: 10m
