name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - main
      # TODO: Remove after testing
      - update-stale-workflow-reusable
  pull_request:

jobs:
  golangci_lint_workflow:
    uses: turbot/steampipe-workflows/.github/workflows/golangci-lint.yml@main
    with:
      timeout: 10m
