name: Stale Issues and PRs
on:
  push:
    branches:
      # TODO: Remove after testing
      - update-stale-workflow-reusable
  schedule:
    - cron: "30 23 * * *"
  workflow_dispatch:
    inputs:
      debugOnly:
        description: Set to true for a dry run
        required: false
        default: "false"
        type: string

jobs:
  stale:
    uses: turbot/steampipe-workflows/.github/workflows/stale.yml@main
    with:
      debugOnly: ${{ github.event.inputs.debugOnly }}
