name: Sync Labels
on:
  push:
    branches:
      # TODO: Remove after testing
      - update-stale-workflow-reusable
  schedule:
    - cron: "30 22 * * *"
  workflow_dispatch:
    inputs:
      dryRun:
        description: Set to true for a dry run
        required: false
        default: "false"
        type: string

jobs:
  sync_labels_workflow:
    uses: turbot/steampipe-workflows/.github/workflows/sync-labels.yml@main
      dryRun: ${{ github.event.inputs.dryRun }}
